/**
 * Build the two deliverables from the readable sources under `src/`:
 *
 *   lib/client.js  — the DSH client bundle. DSH third-party client plugins are
 *                    not plain ES modules: each is a
 *                    `window.__ModuleLoader__.load({ id, factory })`
 *                    registration whose factory receives a CommonJS-style
 *                    `require` (compare any installed dsh-web client bundle).
 *   demo.html      — a self-contained demo page. Inline module scripts run from
 *                    file://, external ones do not, so the component source is
 *                    injected into the page instead of linked.
 *
 *   node build.mjs
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const read = (...parts) => readFileSync(join(root, ...parts), "utf8");
const indent = (text, tabs) => text.split("\n").map((line) => (line === "" ? "" : `${"\t".repeat(tabs)}${line}`)).join("\n");

/** The bundle id is derived, never hand-written: it must equal the package name. */
const packageJson = JSON.parse(read("package.json"));
const packageName = packageJson.name;

/* The patch row's `name` is the id the client-modules service looks this
   bundle up by. When the two disagreed, DSH imported the same file twice and
   aborted web boot with "duplicate factory registration", so fail the build. */
const patchRowName = (read("cordis.patch.yml").match(/name:\s*["']?([^"'\s]+)["']?/) ?? [])[1];
if (patchRowName !== packageName) {
  console.error(`cordis.patch.yml mounts "${patchRowName}" but the package is "${packageName}";`);
  console.error("the client bundle must register the package name, or web boot will fail.");
  process.exit(1);
}

/** Drop the ESM syntax so a source can live inside a factory or an inline script. */
function toPlainSource(source) {
  return source
    .replace(/^import react from "react";$/m, 'const react = require("react");')
    .replace(/^import\s*\{[^}]*\}\s*from\s*"\.\/reasoning-slider\.js";$/m, "")
    .replace(/^export default .*$/m, "")
    .replace(/^export (?=(const|let|var|class|function|async function))/gm, "")
    .trimEnd();
}

/* ---------- lib/client.js ---------- */
const slider = toPlainSource(read("src", "reasoning-slider.js"));
const seat = toPlainSource(read("src", "seat.js"));

const bundle = `/**
 * GENERATED by build.mjs from src/reasoning-slider.js and src/seat.js.
 * Do not edit: change the sources and run \`node build.mjs\`.
 */
window.__ModuleLoader__.load({
	// Must equal this package's name AND the \`name\` of the row in
	// cordis.patch.yml: the client-modules service loads the bundle for the row
	// and registers it under that id. A mismatch makes it import the same file
	// twice and throw "duplicate factory registration", which aborts web boot.
	id: ${JSON.stringify(packageName)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

${indent(slider, 2)}

${indent(seat, 2)}

		exports.REASONING_SLIDER_TAG = REASONING_SLIDER_TAG;
		exports.ReasoningSlider = ReasoningSlider;
		exports.NS = NS;
		exports.ReasoningSeat = ReasoningSeat;
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
`;

mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(join(root, "lib", "client.js"), bundle, "utf8");
console.log(`lib/client.js       ${bundle.length} bytes / ${bundle.split("\n").length} lines`);

/* Gate the build on the artifact actually parsing. A stray backtick inside one
   of the CSS comments in the component's template literals closes that literal
   early and yields a bundle that breaks web boot; this catches it here instead
   of in the running app. */
{
  const probe = join(tmpdir(), `bundle-check-${Date.now()}.mjs`);
  writeFileSync(probe, bundle, "utf8");
  const result = spawnSync(process.execPath, ["--check", probe], { encoding: "utf8" });
  if (result.status !== 0) {
    console.error("\nBUILD FAILED: lib/client.js does not parse.");
    console.error("A backtick inside a CSS comment in a template literal is the usual cause.");
    console.error(String(result.stderr ?? result.error ?? "").split("\n").slice(0, 8).join("\n"));
    process.exit(1);
  }
  console.log("lib/client.js       parses clean (node --check)");
}

/* ---------- demo.html ---------- */
const template = read("demo", "template.html");
const harness = read("src", "demo-harness.js").trimEnd();
const demo = template
  .replace("<!--INJECT:COMPONENT-->", toPlainSource(read("src", "reasoning-slider.js")))
  .replace("<!--INJECT:HARNESS-->", harness);
writeFileSync(join(root, "demo.html"), demo, "utf8");
console.log(`demo.html           ${demo.length} bytes / ${demo.split("\n").length} lines`);

/* ---------- demo/spec.html ---------- */
const specTemplate = read("demo", "spec-template.html");
const specDriver = `
const dark = [{ id: "low", label: "Low", note: "轻量推理" }, { id: "medium", label: "Medium", note: "平衡" }, { id: "high", label: "High", note: "深推理" }];
const withDefault = [{ id: "", label: "默认", note: "由供应商自定" }, ...dark];
const codex = [
  { id: "off", label: "轻度" },
  { id: "low", label: "中" },
  { id: "high", label: "高" },
  { id: "max", label: "极高" },
];
const cases = [
  ["极高 · Max（满配：蓝→紫渐变 + 亮火花，标题转紫）", codex, "max", ["headline", "chevron", "stretch"]],
  ["高 · High（次高档：轻微紫渐变 + 淡火花）", codex, "high", ["headline", "chevron", "stretch"]],
  ["中 · Low（普通档：纯蓝）", codex, "low", ["headline", "chevron", "stretch"]],
  ["轻度 · Off（首档，无填充）", codex, "off", ["headline", "chevron", "stretch"]],
  ["4 档 · 含“默认”档，选中 High", withDefault, "high", []],
  ["3 档 · 选中 Medium", dark, "medium", []],
  ["写入中（busy 脉冲）", dark, "medium", ["busy"]],
  ["禁用（disabled）", dark, "high", ["disabled"]],
  ["展开样式（档位名排在轨道下方）", dark, "low", ["expanded"]],
];
const host = document.querySelector("#cases");
for (const [title, levels, value, flags] of cases) {
  const card = document.createElement("section");
  card.className = "case";
  const heading = document.createElement("h3");
  heading.textContent = title;
  const seat = document.createElement("div");
  seat.className = "seat";
  const slider = document.createElement("dsh-reasoning-slider");
  slider.setAttribute("label", "推理等级");
  if (!flags.includes("expanded") && !flags.includes("headline")) slider.setAttribute("compact", "");
  if (flags.includes("stretch")) slider.style.setProperty("--rs-track-height", "22px");
  if (flags.includes("headline")) slider.setAttribute("subtitle", "DeepSeek-V41-Flash");
  for (const flag of flags) slider.setAttribute(flag, "");
  slider.levels = levels;
  slider.value = value;
  seat.appendChild(slider);
  card.append(heading, seat);
  host.appendChild(card);
}
for (const card of document.querySelectorAll(".case:nth-child(-n+3)")) card.style.gridColumn = "1 / -1";
`;
const spec = specTemplate.replace("<!--INJECT:COMPONENT-->", toPlainSource(read("src", "reasoning-slider.js"))).replace("<!--INJECT:DRIVER-->", specDriver);
writeFileSync(join(root, "demo", "spec.html"), spec, "utf8");
console.log(`demo/spec.html      ${spec.length} bytes / ${spec.split("\n").length} lines`);

/* ---------- demo/compare.html (1:1 against the reference crops) ---------- */
const compareTemplate = read("demo", "compare-template.html");
const compareDriver = `
const levels = [
  { id: "off", label: "轻度" },
  { id: "low", label: "中" },
  { id: "high", label: "高" },
  { id: "max", label: "极高" },
];
const values = ["off", "low", "high", "max"];
const models = [
  { provider: "deepseek", providerLabel: "DeepSeek", model: "flash", label: "DeepSeek-V41-Flash", current: true },
  { provider: "deepseek", providerLabel: "DeepSeek", model: "v4-pro", label: "DeepSeek-V4-Pro" },
  { provider: "openai", providerLabel: "OpenAI", model: "codex", label: "GPT-5.6 Sol" },
];
function addCard(parent, index, dark) {
  const slider = document.createElement("dsh-reasoning-slider");
  slider.setAttribute("card", "");
  slider.setAttribute("chevron", "");
  slider.setAttribute("label", "推理等级");
  if (dark === true) slider.setAttribute("dark", "");
  slider.levels = levels;
  slider.value = values[index];
  slider.subtitle = "DeepSeek-V41-Flash";
  slider.models = models;
  parent.appendChild(slider);
  return slider;
}
const light = document.querySelector("#cards");
const darkHost = document.querySelector("#dark-cards");
levels.forEach((level, index) => addCard(light, index, false));
const last = levels.map((level, index) => addCard(darkHost, index, true)).pop();
// Show the model picker open on the last dark card.
last.shadowRoot.querySelector(".headline .sub").click();
`;
const compare = compareTemplate
  .replace("<!--INJECT:COMPONENT-->", toPlainSource(read("src", "reasoning-slider.js")))
  .replace("<!--INJECT:DRIVER-->", compareDriver);
writeFileSync(join(root, "demo", "compare.html"), compare, "utf8");
console.log(`demo/compare.html   ${compare.length} bytes / ${compare.split("\n").length} lines`);
